<?xml version="1.0" encoding="utf-8"?><Database Name="EscuelaBD" Class="EscuelaModeloLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\EscuelaBD.mdf;Integrated Security=True" SettingsObjectName="WindowsFormAccesoADatos.Windows.Properties.Settings" SettingsPropertyName="EscuelaBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alumnos" Member="Alumno">
    <Type Name="Alumno">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Matricula" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Sexo" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>